### ISSUE TITLE
Singular Matrix error

### ISSUE THREAD

**Issue by westofpluto** [josepatino/pyBK#2]
Hello: When I try to do speaker diarization on a file, i get this error:

Processing file 1 / 1
showName		 audio1
Extracting features
Initial number of features	 360012
UEM file does not exist. The complete audio content is considered.
Number of speech features	 351998
Training the KBM... 
Training pool of 7035 gaussians with a rate of 50 frames
Traceback (most recent call last):
  File "run_speaker_diarization.py", line 76, in <module>
    driver.run_speaker_diarization(input_file=input_file,lbl_file=lbl_file,working_folder=working_folder)
  File "run_speaker_diarization.py", line 59, in run_speaker_diarization
    self.diarization_driver.run_diarization(self.basename,self.wav_file,self.lbl_file,self.rttm_file)
  File "/Users/marcilgen/work/EtherMed/projects/run_speech_to_text/standalone/audio_to_rttm/driver.py", line 159, in run_diarization
    runDiarization(os.path.splitext(os.path.basename(showName))[0],config)
  File "/Users/marcilgen/work/EtherMed/projects/run_speech_to_text/standalone/audio_to_rttm/driver.py", line 66, in runDiarization
    kbm, gmPool = trainKBM(data,config.getint('KBM','windowLength'),windowRate,kbmSize )    
  File "/Users/marcilgen/work/EtherMed/projects/run_speech_to_text/standalone/audio_to_rttm/diarizationFunctions.py", line 268, in trainKBM
    mvn = multivariate_normal(mu,std)
  File "/usr/local/lib/python3.7/site-packages/scipy/stats/_multivariate.py", line 363, in __call__
    seed=seed)
  File "/usr/local/lib/python3.7/site-packages/scipy/stats/_multivariate.py", line 736, in __init__
    self.cov_info = _PSD(self.cov, allow_singular=allow_singular)
  File "/usr/local/lib/python3.7/site-packages/scipy/stats/_multivariate.py", line 163, in __init__
    raise np.linalg.LinAlgError('singular matrix')
numpy.linalg.LinAlgError: singular matrix

How do I fix this?

**Comment by josepatino** [comment]
Hello,
out of intuition and without being able to debug your file myself it seems to me like you're running out of memory due to the length of the file you're processing. If your resources are particularly constrained you can try to play with the 'maximumKBMWindowRate' parameter in the config file. In particular, make it bigger, to a 100/150, until your computer can stand it. This should have some negative effect on performance due to the pool of Gaussian distributions necessary to train the KBM becoming sparser with regard to the overall audio content, but it should nonetheless provide you with a diarization hypothesis.
Please let me know if this helped.
Best,
Jose

**Comment by westofpluto** [comment]
Hi
I set this value as high as 3000 and still get the same error.
The recording is about 60 minutes long.
Are there any other parameters I can tweak to fix this?
Thanks.

**Comment by josepatino** [comment]
Hello @westofpluto,
Well memory is definitely not the problem then. I'm also thinking this could be related to the default value used in the VAD algorithm, which is set to 0. Does your audio include long segments of silence? Please try with more aggressive values for the VAD mode from 1 to 3. 
Best,
Jose
