### ISSUE TITLE
Tried running with own Wav file got error.

### ISSUE THREAD

**Issue by Manu21Iq** [josepatino/pyBK#5]
Number of clusters:	 5
Performing GMM-ML resegmentation...
Traceback (most recent call last):
  File "main.py", line 127, in <module>
    runDiarization(os.path.splitext(os.path.basename(showName))[0],config)
  File "main.py", line 80, in runDiarization
    finalClusteringTableResegmentation,finalSegmentTable = performResegmentation(data,speechMapping, mask,finalClusteringTable[:,bestClusteringID.astype(int)-1],segmentTable,config.getint('RESEGMENTATION','modelSize'),config.getint('RESEGMENTATION','nbIter'),config.getint('RESEGMENTATION','smoothWin'),nSpeechFeatures)
  File "/home/manu/Iqvia_projects/pyBK-master/diarizationFunctions.py", line 600, in performResegmentation
    gmm.fit(data[spkIdxs,:])
  File "/home/manu/anaconda3/lib/python3.8/site-packages/sklearn/mixture/_base.py", line 193, in fit
    self.fit_predict(X, y)
  File "/home/manu/anaconda3/lib/python3.8/site-packages/sklearn/mixture/_base.py", line 246, in fit_predict
    self._m_step(X, log_resp)
  File "/home/manu/anaconda3/lib/python3.8/site-packages/sklearn/mixture/_gaussian_mixture.py", line 678, in _m_step
    self.precisions_cholesky_ = _compute_precision_cholesky(
  File "/home/manu/anaconda3/lib/python3.8/site-packages/sklearn/mixture/_gaussian_mixture.py", line 333, in _compute_precision_cholesky
    raise ValueError(estimate_precision_error_message)
ValueError: Fitting the mixture model failed because some components have ill-defined empirical covariance (for instance caused by singleton or collapsed samples). Try to decrease the number of components, or increase reg_covar.

**Comment by josepatino** [comment]
Hi @Manu21Iq, with this kind of report it is difficult for me to know what could be the source of the problem. Was this using the default configuration? Would you like to share more information about the data? Did you try to debug the processing of the file?

**Comment by LaurensMignolet** [comment]
Hi @Manu21Iq , I get the same errors, did you manage to fix this?

**Comment by josepatino** [comment]
Hi @LaurensMignolet, can you please specify how to reproduce the issue? Would you be able to share with me the .wav file that is giving you problems?

**Comment by LaurensMignolet** [comment]
Hi @josepatino , Thanks for the quick response. I am not sure if i can share the wav file because it is a recording of a meeting. As soon as I get permission i will let you know!

**Comment by josepatino** [comment]
Hi @LaurensMignolet, I understand you might not be able to share it, but could you give me some insight as to the kind of data or the configuration being used? It seems like the problem happens at the resegmentation stage. If you disable the resegmentation does this file still generate some error? Please feel free to contact me also by email at patino@eurecom.fr

**Comment by LaurensMignolet** [comment]
Hello @josepatino I just sent you a mail with the file

**Comment by ADD-eNavarro** [comment]
Hi @josepatino , I'm having the exact same issue here. 
Did you get to a solution to this issue? 

All I have done is install the tool from github, replace the wav files for one of my own, then change the diarizationFunctions.py / py_webrtcvad function to resample the audio when it's not in the accepted values (valid for my testing, but you may want to resample it to the neares value, maybe):

```
   # check argument
    if fs_vad not in [8000, 16000, 32000, 48000]:
        data = resample(data, orig_sr=fs, target_sr=16000)
        fs = fs_vad = 16000
        #raise ValueError('fs_vad must be 8000, 16000, 32000 or 48000.')
```

And then the audio goes in nicely, but I stumble upon the error:

Traceback (most recent call last):
  File "main.py", line 127, in <module>
    runDiarization(os.path.splitext(os.path.basename(showName))[0],config)
  File "main.py", line 80, in runDiarization
    finalClusteringTableResegmentation,finalSegmentTable = performResegmentation(data,speechMapping, mask,finalClusteringTable[:,bestClusteringID.astype(int)-1],segmentTable,config.getint('RESEGMENTATION','modelSize'),config.getint('RESEGMENTATION','nbIter'),config.getint('RESEGMENTATION','smoothWin'),nSpeechFeatures)
  File "C:\Users\eNavarro\Desktop\Diarización cmd\pyBK\pyBK\diarizationFunctions.py", line 607, in performResegmentation
    gmm.fit(data[spkIdxs,:])
  File "C:\Users\eNavarro\Desktop\Diarización cmd\pyBK\env_pyBK\lib\site-packages\sklearn\mixture\_base.py", line 198, in fit
    self.fit_predict(X, y)
  File "C:\Users\eNavarro\Desktop\Diarización cmd\pyBK\env_pyBK\lib\site-packages\sklearn\mixture\_base.py", line 251, in fit_predict
    self._initialize_parameters(X, random_state)
  File "C:\Users\eNavarro\Desktop\Diarización cmd\pyBK\env_pyBK\lib\site-packages\sklearn\mixture\_base.py", line 158, in _initialize_parameters
    self._initialize(X, resp)
  File "C:\Users\eNavarro\Desktop\Diarización cmd\pyBK\env_pyBK\lib\site-packages\sklearn\mixture\_gaussian_mixture.py", line 717, in _initialize
    covariances, self.covariance_type
  File "C:\Users\eNavarro\Desktop\Diarización cmd\pyBK\env_pyBK\lib\site-packages\sklearn\mixture\_gaussian_mixture.py", line 347, in _compute_precision_cholesky
    raise ValueError(estimate_precision_error_message)
ValueError: Fitting the mixture model failed because some components have ill-defined empirical covariance (for instance caused by singleton or collapsed samples). Try to decrease the number of components, or increase reg_covar.


 I solved this one by changing the Gaussian Mixture parameters in performResegmentation function, like so:

        `gmm=mixture.GaussianMixture(n_components=msize,covariance_type='diag', reg_covar=0.0001,weights_init=w_init,means_init=m_init,verbose=0)`

With those changes I could diarize a file of my own.

P.S. I must add that the result was not correct, this tool recognizes 6 speakers where there are only 4 (and 1 is heard so rarely that no other diarization tool does find it). This happened already before changing the reg_covar value.
